[ids]
*

[main]

# Swap Ctrl and Command keys
control = layer(meta)
meta = layer(control)

# Tab switching
[meta]
tab = C-pagedown

[meta+shift]
tab = C-pageup

# Insertion point movement
[control]
left = home
right = end
up = C-home
down = C-end

[alt]
left = C-left
right = C-right
