-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("waybar")
    hl.exec_cmd("~/.config/hypr/scripts/hyprsunset-if-not-gaming.sh")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("elephant")
    hl.exec_cmd("walker --gapplication-service")
    hl.exec_cmd("~/.config/hypr/hotcorner.sh")
    hl.exec_cmd("~/.config/hypr/wallpaper-rotator.sh")
    hl.exec_cmd("~/.config/hypr/scripts/dofus-mouse-remap.sh")
    hl.exec_cmd("synology-drive")
    hl.exec_cmd("librepods --hide")
end)
