-- Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/hypr-colors.lua.tpl.
-- Bare hex (no #) for Hyprland's rgb()/rgba() colour strings.
return {
    bg = "1a1b26",
    bgHighlight = "292e42",
    bgActive = "2f3344",
    fg = "c0caf5",
    fgDark = "a9b1d6",
    comment = "565f89",
    blue = "7aa2f7",
    magenta = "bb9af7",
    red = "f7768e",
}
