# Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/fish-prompt.fish.tpl instead.
# Prompt: user cyan, host blue, cwd green, git purple, arrow blue (root marker red);
# the separators stay muted ({{fgDark}}). Pipestatus keeps fish_color_status.
function fish_prompt --description 'Write out the prompt'
    set -l last_pipestatus $pipestatus
    set -lx __fish_last_status $status
    set -l normal (set_color normal)
    set -l muted (set_color {{fgDark_hex}})

    set -l arrow (set_color {{blue_hex}})'❯'
    if functions -q fish_is_root_user; and fish_is_root_user
        set arrow (set_color {{red_hex}})'#'
    end

    set -l status_color (set_color $fish_color_status)
    set -l prompt_status (__fish_print_pipestatus "[" "]" "|" "$status_color" "$status_color" $last_pipestatus)

    echo -n -s (set_color {{cyan_hex}}) $USER $muted '@' (set_color {{blue_hex}}) (prompt_hostname) ' ' (set_color {{green_hex}}) (prompt_pwd) (set_color {{magenta_hex}}) (fish_vcs_prompt) $normal ' ' $prompt_status $arrow $normal ' '
end
