# Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/fzf.sh.tpl instead.
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#283457 \
  --color=bg:{{bgDark}} \
  --color=border:#27a1b9 \
  --color=fg:{{fg}} \
  --color=gutter:{{bgDark}} \
  --color=header:{{orange}} \
  --color=hl+:{{blue1}} \
  --color=hl:{{blue1}} \
  --color=info:{{dark3}} \
  --color=marker:#ff007c \
  --color=pointer:#ff007c \
  --color=prompt:{{blue1}} \
  --color=query:{{fg}}:regular \
  --color=scrollbar:#27a1b9 \
  --color=separator:{{orange}} \
  --color=spinner:#ff007c \
"
