/* Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/gtk-3.css.tpl instead. */
/* Tokyonight-Dark hardcodes #323449 on views, sidebars and toolbars instead of using its named
   colours. User CSS outranks the theme, so every surface sits on the same ground as the bar and
   kitty: assets/waybar-design/DESIGN.md. */
@define-color theme_base_color {{bg}};
@define-color theme_bg_color {{bg}};

.view,
iconview,
textview,
textview text,
treeview.view,
.sidebar,
.side-panel .view,
scrolledwindow viewport.frame,
.toolbar,
.inline-toolbar,
infobar > revealer > box {
  background-color: {{bg}};
}

/* The ground override above also outranks the theme's selected and hovered rows; restore them
   with the workspace-chip treatment (fg on blue at 16 %). */
.view:selected,
iconview:selected,
treeview.view:selected,
.sidebar:selected,
.sidebar row:selected {
  background-color: alpha({{blue}}, 0.16);
  color: {{fg}};
}

.view:hover,
iconview:hover,
treeview.view:hover {
  background-color: alpha({{fg}}, 0.06);
}
