/* Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/gtk-4-dark.css.tpl instead. */
/* Tokyonight-Dark theme, then every surface on the same ground as the bar and kitty
   (the theme paints views, cards and dialogs on #323449): assets/waybar-design/DESIGN.md. */
@import url("/usr/share/themes/Tokyonight-Dark/gtk-4.0/gtk-dark.css");
@define-color window_bg_color {{bg}};
@define-color view_bg_color {{bg}};
@define-color card_bg_color {{bg}};
@define-color dialog_bg_color {{bg}};
@define-color sidebar_bg_color {{bg}};
@define-color theme_base_color {{bg}};
@define-color theme_bg_color {{bg}};

.view,
textview text,
listview,
columnview,
.sidebar,
.navigation-sidebar,
scrolledwindow viewport.frame {
  background-color: {{bg}};
}

.view:selected,
listview row:selected,
columnview row:selected,
.navigation-sidebar row:selected {
  background-color: alpha({{blue}}, 0.16);
  color: {{fg}};
}
