-- Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/hypr-colors.lua.tpl.
-- Bare hex (no #) for Hyprland's rgb()/rgba() colour strings.
return {
    bg = "{{bg_hex}}",
    bgHighlight = "{{bgHighlight_hex}}",
    bgActive = "{{bgActive_hex}}",
    fg = "{{fg_hex}}",
    fgDark = "{{fgDark_hex}}",
    comment = "{{comment_hex}}",
    blue = "{{blue_hex}}",
    magenta = "{{magenta_hex}}",
    red = "{{red_hex}}",
}
