# Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/kitty.conf.tpl instead.
# Font
font_family                 JetBrainsMono Nerd Font
font_size                   12
bold_font                   auto
italic_font                 auto
bold_italic_font            auto

# Window
window_padding_width 12
remember_window_size        no
initial_window_width        950
initial_window_height       500

# Cursor
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
cursor_trail 3
cursor_trail_decay 0.1 0.4

scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
hide_window_decorations     yes
background_opacity          1.0
dynamic_background_opacity  yes
confirm_os_window_close     0

## Tokyo Night (night) -- same tokens as the bar, see assets/waybar-design/DESIGN.md
foreground              {{fg}}
background              {{bg}}
selection_foreground    {{fg}}
selection_background    {{bgVisual}}

## Cursor colors
cursor                  {{fg}}
cursor_text_color       {{bg}}

## URL underline color when hovering with mouse
url_color               {{green1}}

## Kitty window border colors
active_border_color     {{blue}}
inactive_border_color   {{bgHighlight}}
bell_border_color       {{yellow}}

## OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

## Tab bar colors
active_tab_foreground   {{bg}}
active_tab_background   {{blue}}
inactive_tab_foreground {{fgDark}}
inactive_tab_background {{bgHighlight}}
tab_bar_background      {{bgDark}}

## Colors for marks (marked text in the terminal)
mark1_foreground {{bg}}
mark1_background {{blue}}
mark2_foreground {{bg}}
mark2_background {{magenta}}
mark3_foreground {{bg}}
mark3_background {{cyan}}

## The 16 terminal colors

### black
color0 {{bgDarker}}
color8 {{terminalBlack}}

### red
color1 {{red}}
color9 {{red}}

### green
color2  {{green}}
color10 {{green}}

### yellow
color3  {{yellow}}
color11 {{yellow}}

### blue
color4  {{blue}}
color12 {{blue}}

### magenta
color5  {{magenta}}
color13 {{magenta}}

### cyan
color6  {{cyan}}
color14 {{cyan}}

### white
color7  {{fgDark}}
color15 {{fg}}
