# Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/lazygit-config.yml.tpl instead.
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "{{orange}}"
      - "bold"
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "{{orange}}"
      - "bold"
    optionsTextColor:
      - "{{blue}}"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "{{blue}}"
    cherryPickedCommitBgColor:
      - "{{magenta}}"
    markedBaseCommitFgColor:
      - "{{blue}}"
    markedBaseCommitBgColor:
      - "{{yellow}}"
    unstagedChangesColor:
      - "{{red1}}"
    defaultFgColor:
      - "{{fg}}"
