/* Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/mpris-card-style.css.tpl instead. */
/* Now-playing card (~/.config/mpris-card/card.py): an island under the bar. */
@define-color ground {{ground}};
@define-color line {{line}};
@define-color fg {{fg}};
@define-color fg-dark {{fgDark}};
@define-color comment {{comment}};
@define-color blue {{blue}};

window.card-window,
window.card-window.background {
    background: transparent;
    font-family: "SF Pro Text", sans-serif;
}

window.card-window decoration {
    box-shadow: none;
    margin: 0;
}

.island {
    background: @ground;
    border: 1px solid @line;
    border-radius: 14px;
    padding: 14px;
    min-width: 380px;
}

.cover {
    border-radius: 8px;
    background: alpha(@fg, 0.06);
    min-width: 120px;
    min-height: 120px;
}

.title {
    color: @fg;
    font-weight: 600;
    font-size: 14px;
}

.artist {
    color: @fg-dark;
    font-size: 13px;
}

.album {
    color: @comment;
    font-size: 12px;
}

.time {
    color: @comment;
    font-family: "JetBrainsMono Nerd Font Propo", monospace;
    font-size: 10.5px;
}

.progress {
    min-height: 2px;
    color: @blue;
}

button.control,
button.control:focus,
button.control:active {
    background: transparent;
    border: none;
    box-shadow: none;
    outline: none;
    color: @fg-dark;
    font-family: "JetBrainsMono Nerd Font Propo", monospace;
    font-size: 18px;
    min-width: 32px;
    min-height: 28px;
    border-radius: 8px;
    padding: 0 6px;
    transition: background 120ms ease, color 120ms ease;
}

button.control:hover {
    background: alpha(@blue, 0.16);
    color: @fg;
}
