/* Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/music-placeholder-style.css.tpl instead. */
/* Loading placeholder for the Apple Music scratchpad (~/.config/hypr/scripts/music-placeholder.py). */
@define-color ground {{ground}};
@define-color comment {{comment}};
@define-color blue {{blue}};

window.music-placeholder,
window.music-placeholder.background {
    background: @ground;
}

window.music-placeholder spinner {
    color: @blue;
    min-width: 40px;
    min-height: 40px;
}

window.music-placeholder .title {
    color: @comment;
    font-family: "SF Pro Text", sans-serif;
    font-size: 15px;
}
