/* Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/osd-style.css.tpl instead. */
/* OSD island: same tokens as the bar (Tokyo Night). */
@define-color ground {{ground}};
@define-color line {{line}};
@define-color fg {{fg}};
@define-color yellow {{yellow}};
@define-color blue {{blue}};

window.osd-window {
    background: transparent;
}

window.osd-window decoration {
    box-shadow: none;
    margin: 0;
}

.island {
    background: @ground;
    border: 1px solid @line;
    border-radius: 10px;
    padding: 0 14px;
    min-height: 34px;
}

.track {
    min-height: 2px;
    border-radius: 1px;
    background: alpha(@fg, 0.10);
}

.fill {
    min-height: 2px;
    border-radius: 1px;
}

.fill.volume { background: @yellow; }
.fill.brightness { background: @blue; }
.fill.mute { background: transparent; }
