# Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/slurp-colors.tpl.
# Sourced by screenshot.sh and screen-record.sh: blue selection border, blue 16 % fill, no backdrop
# (a dimmed backdrop exposed a Hyprland damage bug: an undimmed stale rectangle until the pointer moved).
SLURP_ARGS=(-b 00000000 -c {{blue_hex}}ff -s {{blue_hex}}29 -w 1)
