/* Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/walker-style.css.tpl instead. */
/* Tokyo Night (night) island, same tokens as the bar: assets/waybar-design/DESIGN.md */
@define-color fg {{fg}};
@define-color fg-dark {{fgDark}};
@define-color comment {{comment}};
@define-color ground {{bg}};
@define-color blue {{blue}};

* {
  all: unset;
}

* {
  font-family: "JetBrainsMono Nerd Font";
  font-weight: 500;
  font-size: 13px;
  color: @fg-dark;
}

scrollbar {
  opacity: 0;
}

.normal-icons {
  -gtk-icon-size: 18px;
}

.large-icons {
  -gtk-icon-size: 32px;
}

.box-wrapper {
  background: alpha(@ground, 0.85);
  padding: 10px;
  border: 1px solid alpha(@fg, 0.10);
  border-radius: 10px;
}

.preview-box {
}

.box {
}

.search-container {
  padding: 6px 10px;
}

.input placeholder {
  color: @comment;
}

.input {
  color: @fg;
}

.input:focus,
.input:active {
  box-shadow: none;
  outline: none;
}

.content-container {
}

.placeholder {
}

.scroll {
}

.list {
}

child,
child > * {
}

child:hover .item-box {
}

/* Selected entry gets the workspace-chip treatment: fg on blue at 16 %, radius 6. */
child:selected .item-box {
  background: alpha(@blue, 0.16);
  border-radius: 6px;
}

child:selected .item-box * {
  color: @fg;
}

.item-box {
  padding: 0 10px;
  border-radius: 6px;
}

.item-text-box {
  all: unset;
  padding: 8px 0;
}

.item-text {
}

.item-subtext {
  font-size: 0px;
  min-height: 0px;
  margin: 0px;
  padding: 0px;
}

.item-image {
  -gtk-icon-size: 18px;
  margin-right: 10px;
}

.current {
  font-style: italic;
}

.keybind-hints {
  padding: 10px;
  margin-top: 10px;
  color: @comment;
}

.preview {
}
