/* Generated by tools/palette.sh from config/waybar/.config/waybar/colors.css; edit tools/palette/zen-userChrome.css.tpl instead. */
/* Tokyo Night chrome for Zen: toolbar, sidebar and tab strip on the ground colour,
   blue accent, JetBrainsMono in the URL bar. Linked into the profile by `make zen`
   (needs toolkit.legacyUserProfileCustomizations.stylesheets, set in user.js). */
:root {
    --tn-ground: {{bg}};
    --tn-ground-raised: {{bgRaised}};
    --tn-line: {{line}};
    --tn-fg: {{fg}};
    --tn-fg-dark: {{fgDark}};
    --tn-comment: {{comment}};
    --tn-blue: {{blue}};
    --tn-blue-tint: rgba({{blue_rgb}}, 0.16);

    /* Zen / Firefox theme variables, so whichever the build honours applies. */
    --zen-primary-color: var(--tn-blue) !important;
    --zen-colors-primary: var(--tn-ground) !important;
    --zen-colors-secondary: var(--tn-ground-raised) !important;
    --zen-colors-tertiary: var(--tn-ground) !important;
    --zen-colors-border: var(--tn-line) !important;
    --zen-main-browser-background: var(--tn-ground) !important;
    --zen-main-browser-background-toolbar: var(--tn-ground) !important;
    --zen-toolbar-element-bg: var(--tn-blue-tint) !important;
    --zen-branding-bg: var(--tn-ground) !important;
    --zen-dialog-background: var(--tn-ground) !important;
    --zen-themed-toolbar-bg: var(--tn-ground) !important;
    --toolbox-bgcolor: var(--tn-ground) !important;
    --toolbar-bgcolor: var(--tn-ground) !important;
    --toolbar-color: var(--tn-fg) !important;
    --toolbarbutton-icon-fill: var(--tn-fg-dark) !important;
    --toolbarbutton-hover-background: var(--tn-blue-tint) !important;
    --toolbarbutton-active-background: var(--tn-blue-tint) !important;
    --tab-selected-bgcolor: var(--tn-blue-tint) !important;
    --tab-selected-textcolor: var(--tn-fg) !important;
    --urlbar-box-bgcolor: var(--tn-ground-raised) !important;
    --urlbar-box-hover-bgcolor: var(--tn-ground-raised) !important;
    --urlbar-box-active-bgcolor: var(--tn-ground-raised) !important;
    --urlbar-box-text-color: var(--tn-fg) !important;
    --urlbarView-highlight-background: var(--tn-blue-tint) !important;
    --arrowpanel-background: var(--tn-ground) !important;
    --arrowpanel-color: var(--tn-fg) !important;
    --arrowpanel-border-color: var(--tn-line) !important;
    --panel-separator-color: var(--tn-line) !important;
    --focus-outline-color: var(--tn-blue) !important;
    --lwt-accent-color: var(--tn-ground) !important;
    --lwt-text-color: var(--tn-fg) !important;
    --sidebar-background-color: var(--tn-ground) !important;
    --sidebar-text-color: var(--tn-fg) !important;
}

#navigator-toolbox,
#zen-main-app-wrapper,
#zen-appcontent-navbar-container,
#zen-sidebar-splitter,
#TabsToolbar,
#nav-bar,
#titlebar,
.zen-sidebar,
#sidebar-box,
#sidebar-main {
    background: var(--tn-ground) !important;
    border-color: var(--tn-line) !important;
}

/* URL bar: raised ground, hairline, blue ring on focus, monospace input */
#urlbar-background {
    background: var(--tn-ground-raised) !important;
    border: 1px solid var(--tn-line) !important;
    border-radius: 10px !important;
    box-shadow: none !important;
}
#urlbar[focused="true"] > #urlbar-background {
    border-color: var(--tn-blue) !important;
}
#urlbar-input,
#urlbar-input::placeholder {
    font-family: "JetBrainsMono Nerd Font", "JetBrains Mono", monospace !important;
    font-size: 12.5px !important;
    color: var(--tn-fg) !important;
}
#urlbar-input::placeholder {
    color: var(--tn-comment) !important;
}

/* Tabs: quiet by default, blue tint when selected */
.tabbrowser-tab .tab-background {
    border-radius: 8px !important;
}
.tabbrowser-tab[selected] .tab-background,
.tabbrowser-tab[visuallyselected] .tab-background {
    background: var(--tn-blue-tint) !important;
    box-shadow: none !important;
}
.tabbrowser-tab:not([selected]) .tab-label {
    color: var(--tn-fg-dark) !important;
}
.tabbrowser-tab[selected] .tab-label {
    color: var(--tn-fg) !important;
}

/* Popups and menus */
panel, menupopup {
    --panel-background: var(--tn-ground) !important;
    --panel-border-color: var(--tn-line) !important;
    --panel-border-radius: 10px !important;
}
